name: brand_quick_quiz
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_bloc: ^8.0.1
  another_xlider: ^3.0.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  easy_date_timeline: ^0.1.1
  swipe: ^0.0.1
  circular_countdown_timer: ^0.2.3
  share_plus: 6.1.0
  auto_size_text: ^3.0.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  flutter_card_swiper: ^6.0.0
  linear_progress_bar: ^1.1.0
  google_mobile_ads: ^2.0.0
  firebase_core: ^2.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Intel
      fonts:
        - asset: fonts/Inter-Black.ttf
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-ExtraBold.ttf
        - asset: fonts/Inter-ExtraLight.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf



